mode: rule

mixed-port: 7890
redir-port: 7899

# allow-lan: true
bind-address: '127.0.0.1'

log-level: warning

# ipv6: false

external-controller: 127.0.0.1:9090
# secret: "mchaNtwk"
external-ui: ui

# interface-name: eno1

hosts:
  'services.googleapis.cn': 74.125.193.94
  'time.android.com': 203.107.6.88
  'ipv6.msftconnecttest.com': 2a01:111:2003::52 # locked
  'www.msftconnecttest.com': 13.107.4.52 # locked

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  listen: 127.0.0.90:53
  # ipv6: false

  default-nameserver: # bootstrap servers
    - 223.5.5.5
    - 180.76.76.76

  enhanced-mode: fake-ip
  # fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - 'router.asus.com'
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - 'localhost.ptlogin2.qq.com'
    - 'proxy.golang.org'
    # - '+.*' ##! Enable the obsolete redir-host mode, ignores fake-ip. Must enable sniff-tls-sni in this case

##! Enable this if your host have the performance & you don't run SNI proxy
# experimental:
#  sniff-tls-sni: true

  nameserver:
    - tls://dns.qvq.network:853
    - tls://loli.sese.network:853
    - https://101.6.6.6:8443/dns-query # TUNA DNS

  # fake-ip will resolve domain remotely, not needed
  # fallback:
  #   - tls://loli.sese.network:853
  #   - https://101.6.6.6:8443/dns-query # TUNA DNS
  #   - tls://8.8.8.8:853

tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true
  auto-detect-interface: true
  # dns-hijack:
  #   - 198.18.0.2:53

proxies:
  # empty, see proxy-providers

proxy-groups:
  - name: Proxy
    type: select
    # disable-udp: true
    # interface-name: en1
    use:
      - service
      - misc

  - name: Adblock
    type: select
    proxies:
      - REJECT
      - Proxy
      - DIRECT

  - name: Geowall
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - service
      - misc

  - name: Game
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - service
      - misc

  - name: Steam
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - service
      - misc

  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
    use:
      - service
      - misc

  - name: Telegram
    type: select
    proxies:
      - Proxy
    use:
      - service
      - misc

proxy-providers:
  service: ##! your service provider
    type: http
    url: "https://example.invalid/proxy.yaml" ##! change this to your real subscription URL
    interval: 3600
    path: ./provider/service.yaml
    health-check:
      enable: true
      interval: 3600
      url: http://cp.cloudflare.com/generate_204
  misc:
    type: file
    path: ./provider/misc.yaml ##! local provider
    health-check:
      enable: true
      interval: 3600
      url: http://cp.cloudflare.com/generate_204
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://gh.chapro.xyz/raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
    path: ./ruleset/reject.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://geosite.mcha.cloud/cn.yaml"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://geosite.mcha.cloud/private.yaml"
    path: ./ruleset/private.yaml
    interval: 86400
  unbreak:
    type: http
    behavior: domain
    url: "https://gh.chapro.xyz/raw.githubusercontent.com/mchaNetwork/rules/master/clash/unbreak.yaml"
    path: ./ruleset/unbreak.yaml
    interval: 86400
  steam:
    type: http
    behavior: domain
    url: "https://gh.chapro.xyz/raw.githubusercontent.com/mchaNetwork/rules/master/clash/steam.yaml"
    path: ./ruleset/steam.yaml
    interval: 86400
  paypal:
    type: http
    behavior: domain
    url: "https://gh.chapro.xyz/raw.githubusercontent.com/mchaNetwork/rules/master/clash/paypal.yaml"
    path: ./ruleset/paypal.yaml
    interval: 86400

rules:
  # - SCRIPT,quic,REJECT
  - RULE-SET,unbreak,Proxy
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,Adblock
  # - RULE-SET,steam,Steam
  - RULE-SET,paypal,PayPal
  - DOMAIN-SUFFIX,openai.com,Geowall
  - DOMAIN-KEYWORD,google,Geowall
  - DOMAIN-KEYWORD,bing,Geowall
  # - GEOIP,GAME,Game
  - RULE-SET,direct,DIRECT
  - GEOIP,TELEGRAM,Telegram
  - GEOIP,PRIVATE,DIRECT
  - GEOIP,CN,DIRECT
  - PROCESS-NAME,tailscaled,DIRECT
  - PROCESS-NAME,croc,DIRECT
  - MATCH,Proxy

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
